name: groc_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  http: ^1.1.0
  jaguar_jwt: ^3.0.0
  maps_toolkit: ^3.0.0
  mongo_dart: ^0.9.3
  mongo_pool: ^1.3.2
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
